import Head from "next/head";
import Image from "next/image";
import styles from "../../components/styles/Home.module.css";
import Navbar from "../../components/Navbar";
import Login from "../../components/auth/adminLoginForm";


export default function AdminLogin() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Admin Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Login />
    </div>
  );
}
